// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgx_W2C9hikq4SY0Q4HlWl4fkx7QHUM34',
    appId: '1:668846874331:web:d3a0a4ba870c22877d36fe',
    messagingSenderId: '668846874331',
    projectId: 'feasta-catering-system',
    authDomain: 'feasta-catering-system.firebaseapp.com',
    storageBucket: 'feasta-catering-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJGhqy1oJ2fJ6GpBa60q33GI3fsDclQU',
    appId: '1:668846874331:android:93bf5327f1fefb127d36fe',
    messagingSenderId: '668846874331',
    projectId: 'feasta-catering-system',
    storageBucket: 'feasta-catering-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmb8-uGEDDxIn1HPokAAQk9O3BvuALbjM',
    appId: '1:668846874331:ios:a294daec18e300af7d36fe',
    messagingSenderId: '668846874331',
    projectId: 'feasta-catering-system',
    storageBucket: 'feasta-catering-system.firebasestorage.app',
    iosClientId: '668846874331-13r2vf1v0qgh4tpngfqf0va0sfkcuqtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.feasta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmb8-uGEDDxIn1HPokAAQk9O3BvuALbjM',
    appId: '1:668846874331:ios:a294daec18e300af7d36fe',
    messagingSenderId: '668846874331',
    projectId: 'feasta-catering-system',
    storageBucket: 'feasta-catering-system.firebasestorage.app',
    iosClientId: '668846874331-13r2vf1v0qgh4tpngfqf0va0sfkcuqtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.feasta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgx_W2C9hikq4SY0Q4HlWl4fkx7QHUM34',
    appId: '1:668846874331:web:d82b11b567b7a9817d36fe',
    messagingSenderId: '668846874331',
    projectId: 'feasta-catering-system',
    authDomain: 'feasta-catering-system.firebaseapp.com',
    storageBucket: 'feasta-catering-system.firebasestorage.app',
  );

}